### PR TITLE
Add support for prepending a prefix to the start of a command

### PR DESCRIPTION
**Pull request by wei2912**
This pull request adds support for appending a prefix to the start of a command. It combines multiple regular expressions into one which is more efficient.

In case you're confused, the first commit's message has a typo in it which I did not notice till now.

### CODE REVIEW

**Comment by sarenji** [comment]
Very cool. So this means (by default) you can call the bot by typing `%`?

**Comment by sarenji** [comment]
Thanks for working on this!

**Comment by wei2912** [comment]
You're welcome :)

To answer your question, yes, you can do stuff like "%bling", shown in the example.

There's more coming. I'm using pyrc for an IRC bot project and decided to help expand on it :) Of course, I'll keep it lightweight at the same time.

**Comment by sarenji** [comment]
Much appreciated :)

**Pull request merged**
